openapi: 3.0.3
info:
  title: Sample Title
  description: Description about this API Collection
  termsOfService: https://www.google.co.in/
  contact:
    name: deepak
    url: https://www.google.co.in/
    email: deepakpalakkal795@gmail.com
  license:
    name: license_1
    url: https://www.google.co.in/
  version: 0.0.1
servers:
  - url: https://www.google.com/
    description: testing url
  - url: https://www.google.co.in/
    description: staging url
  - url: https://www.google.co.in/
    description: pre-prod url
  - url: https://www.{username}.com:{port}/{version}
    description: test url
    variables:
      username:
        default: demo
        description: host name
      port:
        enum:
          - "8443"
          - "80"
        default: "8443"
      version:
        default: v1
paths: {}
